# Generated by Django 2.2 on 2019-05-12 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('idAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthDate', models.DateField()),
                ('department', models.CharField(choices=[('IG', 'IG'), ('GBA', 'GBA'), ('EGC', 'EGC'), ('MAT', 'MAT'), ('MEA', 'MEA'), ('MI', 'MI'), ('MSI', 'MSI'), ('SE', 'SE'), ('STE', 'STE')], max_length=12)),
                ('year_in_school', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5')], max_length=4)),
                ('githubLink', models.URLField(blank=True, null=True)),
                ('linkedInLink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('nameCat', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('idGroup', models.AutoField(primary_key=True, serialize=False)),
                ('nameGroup', models.CharField(max_length=42, unique=True)),
                ('idAccountGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('idPubli', models.AutoField(primary_key=True, serialize=False)),
                ('titlePubli', models.CharField(max_length=42)),
                ('ContentPubli', models.TextField(max_length=420)),
                ('datePublished', models.DateTimeField(default=django.utils.timezone.now)),
                ('idAccountPubli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('idCatPubli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAccountJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('idGroupJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('idFile', models.AutoField(primary_key=True, serialize=False)),
                ('nameFile', models.CharField(max_length=100)),
                ('fileFile', models.FileField(upload_to='file/')),
                ('idPubliFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=420)),
                ('commentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('idAccountC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('idPubliC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='groupCat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Group'),
        ),
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('idAccountB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('idGroupB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
    ]
