# Generated by Django 2.2 on 2019-05-09 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=42)),
                ('firstName', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=254)),
                ('birthDate', models.DateField()),
                ('department', models.CharField(choices=[('IG', 'IG'), ('GBA', 'GBA'), ('EGC', 'EGC'), ('MAT', 'MAT'), ('MEA', 'MEA'), ('MI', 'MI'), ('MSI', 'MSI'), ('SE', 'SE'), ('STE', 'STE')], max_length=12)),
                ('year_in_school', models.CharField(choices=[('A1', '1er année'), ('A2', '2nd année'), ('A3', '3eme année'), ('A4', '4eme année'), ('A5', '5eme année')], max_length=12)),
                ('githubLink', models.URLField(blank=True, null=True)),
                ('linkedInLink', models.CharField(blank=True, max_length=200, null=True)),
                ('idAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('NameCat', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('idGroup', models.AutoField(primary_key=True, serialize=False)),
                ('NameGroup', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('idPubli', models.AutoField(primary_key=True, serialize=False)),
                ('TitlePubli', models.CharField(max_length=42)),
                ('ContentPubli', models.TextField(max_length=420)),
                ('datePublished', models.DateTimeField(default=django.utils.timezone.now)),
                ('idAccountPubli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('idCatPubli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAccountB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('idGroupB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('idFile', models.AutoField(primary_key=True, serialize=False)),
                ('NameFile', models.CharField(max_length=100)),
                ('fileFile', models.FileField(upload_to='file/')),
                ('idPubliFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=420)),
                ('commentDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('idAccountC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('idPubliC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('idAccountB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('idGroupB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
    ]
