# Generated by Django 2.2 on 2019-05-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publication_idgrouppubli'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
                ('publiFile', models.ForeignKey(db_column='publiFile', on_delete=django.db.models.deletion.CASCADE, to='app.Publication')),
            ],
        ),
    ]
