# Generated by Django 2.2 on 2019-05-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminAccount', models.ForeignKey(db_column='adminAccount', on_delete=django.db.models.deletion.CASCADE, to='app.Account')),
                ('adminGroup', models.ForeignKey(db_column='adminGroup', on_delete=django.db.models.deletion.CASCADE, to='app.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='idCatPubli',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
