# Generated by Django 2.2 on 2019-05-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190515_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='filef',
        ),
    ]
