# Generated by Django 2.2 on 2019-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190515_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filef',
        ),
        migrations.RemoveField(
            model_name='file',
            name='nameFile',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
