# Generated by Django 2.2 on 2019-05-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190515_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='filef',
        ),
    ]
